apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: noted-media-content
  namespace: default
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
