env:
  SECRET_KEY: "{{.Values.djangoSecretKey}}"
  DB_HOST: main-postgres.default.svc.cluster.local
  DB_USER:
    valueFrom:
      secretKeyRef:
        name: spoosk-pgsql-creds
        key: user
  DB_NAME:
    valueFrom:
      secretKeyRef:
        name: spoosk-pgsql-creds
        key: database
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: spoosk-pgsql-creds
        key: password
  DB_PORT: 6432
  ALLOWED_HOSTS: "*"
  DJANGO_DEBUG: "True"
  PYTHONUNBUFFERED: "1"

imagePullSecrets:
  - name: gitlab-cr

replicaCount: 1

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
  hosts:
    - host: "{{ .Values.CI_FQDN }}"
      paths:
        - "/"