# Generated by Django 4.2.5 on 2023-10-23 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resorts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkiReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='skiresort',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='begin_season',
            field=models.CharField(blank=True, help_text='start of the ski season month', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='children_school',
            field=models.IntegerField(blank=True, help_text="'1' if resort has training school for children, '0' if has not", null=True),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='distance_airport',
            field=models.IntegerField(blank=True, help_text='km from airport', null=True),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='distance_railway',
            field=models.IntegerField(blank=True, help_text='km from railway station', null=True),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='end_season',
            field=models.CharField(blank=True, help_text='end of the ski season month', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='equip_rental',
            field=models.IntegerField(blank=True, help_text="'1' if resort has equipment rental, '0' if has not", null=True),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='evening_skiing',
            field=models.IntegerField(blank=True, help_text="'1' if resort has evening skiing, '0' if has not", null=True),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='freeride',
            field=models.IntegerField(blank=True, help_text="'1' if resort has freeride, '0' if has not", null=True),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='id_resort',
            field=models.CharField(db_column='ID_resort', help_text="avalable: 'Sheregesh', 'Roza_hutor', 'Gazprom', 'Elbrus', 'Dombay', 'Big_wood', 'Arkhyz'", max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='image',
            field=models.ImageField(help_text="url of small image for resort's card", null=True, upload_to='static/image/card', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='ind_training',
            field=models.IntegerField(blank=True, help_text="have no idea what's this field for", null=True),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='info',
            field=models.TextField(blank=True, help_text='resort description', null=True),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='link_ofsite',
            field=models.CharField(blank=True, help_text="url of resort's website", null=True),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='list_month',
            field=models.TextField(blank=True, help_text='list of months which cover the ski season', null=True),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='main_resort_img',
            field=models.ImageField(help_text="url of large image for resort's page header", null=True, upload_to='static/image/resorts', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='school',
            field=models.IntegerField(blank=True, help_text="'1' if resort has ski school, '0' if has not", null=True),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='snowpark',
            field=models.IntegerField(blank=True, help_text="'1' if resort has snowpark, '0' if has not", null=True),
        ),
        migrations.AddField(
            model_name='skireview',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resorts.skiresort'),
        ),
    ]
