# Generated by Django 4.2.5 on 2023-11-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0004_remove_skiresort_rating_skiresort_max_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='skireview',
            name='add_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
