# Generated by Django 4.2.5 on 2023-11-13 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0005_skireview_add_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='skiresort',
            name='link_skipasses',
            field=models.CharField(blank=True, help_text="url of skipasses page on resort's website", null=True),
        ),
        migrations.CreateModel(
            name='ResortImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='static/image/resorts')),
                ('add_at', models.DateTimeField(auto_now=True)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resorts.skiresort')),
            ],
        ),
    ]
