# Generated by Django 4.2.5 on 2023-12-04 13:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0007_skireview_approved_alter_resortimage_add_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skireview',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='skireview',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_reviews', to='resorts.skiresort'),
        ),
        migrations.AlterField(
            model_name='skireview',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
