# Generated by Django 4.2 on 2023-05-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0007_skiresort_link_ofsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='skiresort',
            name='main_resort_img',
            field=models.ImageField(null=True, upload_to='static/image/resorts', verbose_name='image'),
        ),
    ]
