# Generated by Django 4.2.5 on 2023-12-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0008_alter_skireview_rating_alter_skireview_resort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skiresort',
            name='link_map',
            field=models.CharField(blank=True, help_text="url of resort's map", null=True),
        ),
        migrations.AlterField(
            model_name='resortimage',
            name='image',
            field=models.ImageField(upload_to='resorts'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(upload_to='reviews'),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='image',
            field=models.ImageField(help_text="url of small image for resort's card", null=True, upload_to='resorts/mini', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='skiresort',
            name='main_resort_img',
            field=models.ImageField(help_text="url of large image for resort's page header", null=True, upload_to='resorts/maxi', verbose_name='image'),
        ),
    ]
