# Generated by Django 4.2.5 on 2024-01-16 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resorts', '0010_alter_resortimage_image_alter_skiresort_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skiresort',
            name='resort_map',
            field=models.ImageField(help_text="url of image for resort's map", null=True, upload_to='resorts/maps'),
        ),
        migrations.AddField(
            model_name='skiresort',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
